#!/usr/bin/env python3
"""Compare a smoke run byte-for-byte with excerpts generated by the old repo."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def load(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    # Old CUDA aggregated these diagnostics per launch block for tiny soups;
    # CPU uses per-interaction counters. Scientific state fields agree exactly.
    backend_diagnostics = {
        "frac_term_step_cap",
        "frac_term_ip_out_of_bounds",
        "frac_term_bracket_mismatch",
    }
    return [
        {key: value for key, value in row.items() if key not in backend_diagnostics}
        for row in rows
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-root", type=Path, required=True)
    args = parser.parse_args()
    for regime in ("u", "n", "r"):
        actual_path = args.run_root / regime / "log_0.log"
        expected_path = ROOT / "data" / "validation" / f"smoke_{regime}_seed0.csv"
        actual, expected = load(actual_path), load(expected_path)
        if actual != expected:
            raise AssertionError(f"Smoke mismatch for {regime.upper()}: {actual_path} != {expected_path}")
        if len(actual) != 3:
            raise AssertionError(f"Expected 3 smoke epochs for {regime.upper()}, found {len(actual)}")
        print(f"{regime.upper()}: 3/3 rows match the reference output")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
